"""add MITRE ATTACK fields

Revision ID: f7bb5ff7bf50
Revises: 337d601634a3
Create Date: 2026-08-20 18:36:19.509777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7bb5ff7bf50'
down_revision: Union[str, Sequence[str], None] = '337d601634a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_events', sa.Column('mitre_technique_id', sa.String(length=20), nullable=True))
    op.add_column('security_events', sa.Column('mitre_technique_name', sa.String(length=150), nullable=True))
    op.add_column('security_events', sa.Column('mitre_tactic', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_events', 'mitre_tactic')
    op.drop_column('security_events', 'mitre_technique_name')
    op.drop_column('security_events', 'mitre_technique_id')
    # ### end Alembic commands ###
